{
 "title": "XRPL EVM Benchmarking Tool by Cumulo",
 "description": "Measure the technical performance of the XRPL EVM Testnet through an automated benchmarking script that:\n\nSends real EVM-compatible transactions\nRecords inclusion time (latency)\nMeasures gas used per transaction\nCalculates averages, success rates, and standard deviation\nExposes all metrics to Prometheus for Grafana dashboards",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Benchmarking Tool metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <img src=\"https://cumulo.pro/images/xrp.png\" alt=\"Logo\" style=\"height: 150px;\"> <!-- Ajusta la altura según sea necesario -->\n    <h2>XRPL EVM Benchmarking Tool</h2>\n    <h5>by <a href=\"https://cumulo.pro\">Cumulo</a></h5>\n    <p><a href=\"https://github.com/Cumulo-pro/xrplevmTools/blob/main/Benchmarking%20Tool/metrics.md\">Benchmarking Metrics</a>\n</div>"
   }
  },
  {
   "title": "Total  transactions ",
   "type": "stat",
   "description": "Total number of transactions sent during the benchmark",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xrpl_tx_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed transactions",
   "type": "stat",
   "description": "Total number of failed transactions",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "xrpl_tx_failures_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transactions  status",
   "type": "gauge",
   "description": "Count of transactions grouped by status",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xrpl_tx_status_total", "legendFormat": "success" }
   ]
  },
  {
   "title": "Success transactions ",
   "type": "stat",
   "description": "Success ratio of transactions (range: 0 to 1)",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "evm_tx_success_rate", "legendFormat": "__auto" }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Standard deviation latency ",
   "type": "stat",
   "description": "Standard deviation of execution latency (ms)",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "evm_tx_exec_time_stddev", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Standard deviation latency serie",
   "type": "timeseries",
   "description": "Standard deviation of execution latency (ms)",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "evm_tx_exec_time_stddev", "legendFormat": "latency ms" }
   ]
  },
  {
   "title": "Average  latency",
   "type": "stat",
   "description": "Average time (ms) between sending and confirming transactions",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xrpl_avg_latency_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average latency serial",
   "type": "timeseries",
   "description": "Average time (ms) between sending and confirming transactions",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "xrpl_avg_latency_ms", "legendFormat": "Average time (ms)" }
   ]
  },
  {
   "title": "Average gas consumed",
   "type": "stat",
   "description": "Average gas consumed per transaction",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xrpl_avg_gas_used", "legendFormat": "number times time out" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 25 },
   "targets": [
    { "expr": "xrpl_avg_gas_used", "legendFormat": "gas" }
   ]
  },
  {
   "title": "Transaction latency distribution ",
   "type": "timeseries",
   "description": "Distribution of transaction confirmation latency in ms, is a histogram of transaction inclusion latency. It measures how long it takes, in milliseconds, from the time a transaction is sent (sendTransaction) until it is committed (receipt = tx.wait()).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "xrpl_tx_latency_histogram_ms_bucket",
     "legendFormat": "le: {{le}}"
    }
   ]
  },
  {
   "title": "Extended Benchmark Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Wallet balance",
   "type": "stat",
   "description": "Wallet balance (in ETH) at benchmark start",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xrpl_wallet_balance_eth",
     "legendFormat": " current size of the overflow in the request list"
    }
   ]
  },
  {
   "title": "Average transaction fee ",
   "type": "stat",
   "description": "Average transaction fee paid (in ETH)",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xrpl_avg_fee_paid", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total duration benchmark",
   "type": "timeseries",
   "description": "Total duration of the benchmark (in milliseconds) including quantiles",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 40 },
   "targets": [
    { "expr": "xrpl_benchmark_duration_ms", "legendFormat": "quantile: {{quantile}}" }
   ]
  }
 ]
}